---
version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "github-actions"]

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies", "go"]

  - package-ecosystem: npm
    directory: /themes/jmpa
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies", "javascript"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "docker"]
