baseURL = "https://jmpa.io"
languageCode = "en-us"
title = "jmpa.io"
theme = "jmpa"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Courses"
    pre = "pen-tool"
    url = "/courses/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
