baseURL = "https://jmpa.io"
languageCode = "en-us"
title = "jmpa.io"
theme = "jmpa"

[Params]
  description = "Hello World?"
  images = ["https://raw.githubusercontent.com/apvarun/digital-garden-hugo-theme/main/images/digital-garden-logo.png"]

  # custom params.
  custom_css = ["css/style.css"]
  logo = "https://raw.githubusercontent.com/jmpa-io/.github/master/logo.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Courses"
    url = "/courses"
    weight = 2
  [[menu.main]]
    name = "Stack"
    url = "/stack"
    weight = 3

  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/jmpa-io"
    weight = 1
  [[menu.social]]
    name = "Email"
    url = "mailto:support@jmpa.io"
    weight = 2

# syntax highlighting.
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

# setup 404.
[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404
